# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@pixi/colord-2.9.6" = {
      name = "_at_pixi_slash_colord";
      packageName = "@pixi/colord";
      version = "2.9.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pixi/colord/-/colord-2.9.6.tgz";
        sha512 = "nezytU2pw587fQstUu1AsJZDVEynjskwOL+kibwcdxsMBFqPsFFNA7xl0ii/gXuDi6M0xj3mfRJj8pBSc2jCfA==";
      };
    };
    "@types/css-font-loading-module-0.0.12" = {
      name = "_at_types_slash_css-font-loading-module";
      packageName = "@types/css-font-loading-module";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/css-font-loading-module/-/css-font-loading-module-0.0.12.tgz";
        sha512 = "x2tZZYkSxXqWvTDgveSynfjq/T2HyiZHXb00j/+gy19yp70PHCizM48XFdjBCWH7eHBD0R5i/pw9yMBP/BH5uA==";
      };
    };
    "@types/earcut-2.1.4" = {
      name = "_at_types_slash_earcut";
      packageName = "@types/earcut";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/earcut/-/earcut-2.1.4.tgz";
        sha512 = "qp3m9PPz4gULB9MhjGID7wpo3gJ4bTGXm7ltNDsmOvsPduTeHp8wSW9YckBj3mljeOh4F0m2z/0JKAALRKbmLQ==";
      };
    };
    "@webgpu/types-0.1.60" = {
      name = "_at_webgpu_slash_types";
      packageName = "@webgpu/types";
      version = "0.1.60";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webgpu/types/-/types-0.1.60.tgz";
        sha512 = "8B/tdfRFKdrnejqmvq95ogp8tf52oZ51p3f4QD5m5Paey/qlX4Rhhy5Y8tgFMi7Ms70HzcMMw3EQjH/jdhTwlA==";
      };
    };
    "@xmldom/xmldom-0.8.10" = {
      name = "_at_xmldom_slash_xmldom";
      packageName = "@xmldom/xmldom";
      version = "0.8.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmldom/xmldom/-/xmldom-0.8.10.tgz";
        sha512 = "2WALfTl4xo2SkGCYRt6rDTFfk9R1czmBvUQy12gK2KuRKIpWEhcbbzy8EZXtz/jkRqHX8bFEc6FC1HjX4TUWYw==";
      };
    };
    "earcut-2.2.4" = {
      name = "earcut";
      packageName = "earcut";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/earcut/-/earcut-2.2.4.tgz";
        sha512 = "/pjZsA1b4RPHbeWZQn66SWS8nZZWLQQ23oE3Eam7aroEFGEvwKAsJfZ9ytiEMycfzXWpca4FA9QIOehf7PocBQ==";
      };
    };
    "eventemitter3-5.0.1" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-5.0.1.tgz";
        sha512 = "GWkBvjiSZK87ELrYOSESUYeVIc9mvLLf/nXalMOS5dYrgZq9o5OVkbZAVM06CVxYsCwH9BDZFPlQTlPA1j4ahA==";
      };
    };
    "gifuct-js-2.1.2" = {
      name = "gifuct-js";
      packageName = "gifuct-js";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gifuct-js/-/gifuct-js-2.1.2.tgz";
        sha512 = "rI2asw77u0mGgwhV3qA+OEgYqaDn5UNqgs+Bx0FGwSpuqfYn+Ir6RQY5ENNQ8SbIiG/m5gVa7CD5RriO4f4Lsg==";
      };
    };
    "ismobilejs-1.1.1" = {
      name = "ismobilejs";
      packageName = "ismobilejs";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ismobilejs/-/ismobilejs-1.1.1.tgz";
        sha512 = "VaFW53yt8QO61k2WJui0dHf4SlL8lxBofUuUmwBo0ljPk0Drz2TiuDW4jo3wDcv41qy/SxrJ+VAzJ/qYqsmzRw==";
      };
    };
    "js-binary-schema-parser-2.0.3" = {
      name = "js-binary-schema-parser";
      packageName = "js-binary-schema-parser";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-binary-schema-parser/-/js-binary-schema-parser-2.0.3.tgz";
        sha512 = "xezGJmOb4lk/M1ZZLTR/jaBHQ4gG/lqQnJqdIv4721DMggsa1bDVlHXNeHYogaIEHD9vCRv0fcL4hMA+Coarkg==";
      };
    };
    "parse-svg-path-0.1.2" = {
      name = "parse-svg-path";
      packageName = "parse-svg-path";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-svg-path/-/parse-svg-path-0.1.2.tgz";
        sha512 = "JyPSBnkTJ0AI8GGJLfMXvKq42cj5c006fnLz6fXy6zfoVjJizi8BNTpu8on8ziI1cKy9d9DGNuY17Ce7wuejpQ==";
      };
    };
    "pixi.js-8.9.2" = {
      name = "pixi.js";
      packageName = "pixi.js";
      version = "8.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixi.js/-/pixi.js-8.9.2.tgz";
        sha512 = "oLFBkOOA/O6OpT5T8o05AxgZB9x9yWNzEQ+WTNZZFoCvfU2GdT4sFTjpVFuHQzgZPmAm/1IFhKdNiXVnlL8PRw==";
      };
    };
  };
  args = {
    name = "relearning";
    packageName = "relearning";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."@pixi/colord-2.9.6"
      sources."@types/css-font-loading-module-0.0.12"
      sources."@types/earcut-2.1.4"
      sources."@webgpu/types-0.1.60"
      sources."@xmldom/xmldom-0.8.10"
      sources."earcut-2.2.4"
      sources."eventemitter3-5.0.1"
      sources."gifuct-js-2.1.2"
      sources."ismobilejs-1.1.1"
      sources."js-binary-schema-parser-2.0.3"
      sources."parse-svg-path-0.1.2"
      sources."pixi.js-8.9.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
